"""Changes Venue.website_link to Venue.website

Revision ID: f1150c28f8e7
Revises: 00b0b3028d11
Create Date: 2022-08-12 15:54:35.007610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1150c28f8e7'
down_revision = '00b0b3028d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'website_link', new_column_name='website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'website', new_column_name='website_link')
    # ### end Alembic commands ###
